executable            = drawPulseShapeTBCondor.sh
arguments             = $(cfg)
output                = /afs/cern.ch/user/s/spalluot/MTD/TB_FNAL_Mar23/Lab5015Analysis/scripts/jobs/job_drawPulseShape.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/user/s/spalluot/MTD/TB_FNAL_Mar23/Lab5015Analysis/scripts/jobs/job_drawPulseShape.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/user/s/spalluot/MTD/TB_FNAL_Mar23/Lab5015Analysis/scripts/jobs/job_drawPulseShape.$(ClusterId).$(ProcId).log
+JobFlavour = "longlunch"
queue cfg from list_cfg_drawPulseShapeTB_LYSO824.txt